# Generated by Django 3.1.1 on 2021-08-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitech_audit_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselogging',
            name='creator_agent',
            field=models.CharField(max_length=355, null=True, verbose_name='Creator Agent'),
        ),
    ]
